<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-MTFJEHHC" name="sff2.GoogleSmokeTest2" tests="3" failures="1" timestamp="15 Apr 2018 14:10:34 GMT" time="70.318" errors="0">
  <testcase name="googleSmokeTest" time="23.923" classname="sff2.GoogleSmokeTest2"/>
  <testcase name="googleSmokeTest" time="24.972" classname="sff2.GoogleSmokeTest2">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at sff2.GoogleSmokeTest2.searchGoogle(GoogleSmokeTest2.java:147)
at sff2.GoogleSmokeTest2.googleSmokeTest(GoogleSmokeTest2.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- googleSmokeTest -->
  <testcase name="googleSmokeTest" time="21.423" classname="sff2.GoogleSmokeTest2"/>
</testsuite> <!-- sff2.GoogleSmokeTest2 -->
